#!/bin/bash

# What is the project called
project_name='Arx'

# Some additional arx-specific build options
cmake_options[minimal]='-DBUILD_EDIT_LOADSAVE=0'
cmake_options[unity]='-DUNITY_BUILD=1'
cmake_options[xtra]='-DDEBUG_EXTRA=1'
cmake_options[boostfs]='-DUSE_NATIVE_FS=0'

# The environments for these don't have Qt installed - disable the crash reporter
cmake_options[gcc-freebsd-9.1-i686]+=" -DBUILD_CRASHREPORTER=0"
cmake_options[gcc-armv6j-hf]+=" -DBUILD_CRASHREPORTER=0"

arx_use_qt4="-DUSE_QT5=0 -DWITH_QT=4"
arx_use_qt5="-DUSE_QT4=0 -DWITH_QT=5"
cmake_options[olddeps]+=" $arx_use_qt4 -DWITH_SDL=1"
cmake_options[m32]+=" $arx_use_qt4"
cmake_options[msvc-9.0-32]+=" $arx_use_qt4"
cmake_options[msvc-9.0-64]+=" $arx_use_qt4"
cmake_options[msvc-10.0-32]+=" $arx_use_qt5"
cmake_options[msvc-11.0-32]+=" $arx_use_qt5"
cmake_options[msvc-11.0-64]+=" $arx_use_qt5"
cmake_options[msvc-12.0-32]+=" $arx_use_qt5"
cmake_options[msvc-12.0-64]+=" $arx_use_qt5"
cmake_options[gcc-armv6j-hf]+=" -DWITH_SDL=1"

# Compiler for builds that test library/config compatability
default_compiler='gcc-4.8'

# Declare directories containing source code (for cppcheck and flawfinder)
source_directories+=(
	"$repo/tools"
)
include_directories+=(
	-I "$repo/tools"
)

# TODO temp workaround for clang + libc++ + unity build = OOM/crash
compiler_options[libcxx]+=" -fPIE"

# Finally, define the used build types.
# Each build type is an underscore-seperated list of tokens defined in
# cmake_options, compiler_options and make_options.
build_types=(
	
	# Static analyzers and style checks
	
	'clang-analyzer'
	'clang-analyzer_unity'
	
	'cppcheck'
	
	'flawfinder'
	
	# Test different compilers/stdlibs and versions
	
	'clang-3.1_libcxx_debug'
	'clang-3.1_libcxx_unity'
	
	'clang-3.2_libcxx_debug'
	'clang-3.2_libcxx_unity'
	
	'clang-3.3_libcxx_debug'
	'clang-3.3_libcxx_unity'
	
	'clang-3.4_libcxx_debug'
	'clang-3.4_libcxx_unity'
	
	'clang-dev_libcxx_debug'
	'clang-dev_libcxx_unity'
	
	'clang-dev_libcxx_m32_debug'
	
	'clang_libstdcxx_debug'
	'clang_libstdcxx_unity'
	
	'ekopath_debug'
	'ekopath_unity'
	
	'icc_debug'
	'icc_unity'
	
	'gcc-4.3_debug'
	'gcc-4.3_unity'
	
	'gcc-4.4_debug'
	'gcc-4.4_unity'
	
	'gcc-4.5_debug'
	'gcc-4.5_unity'
	
	'gcc-4.6_debug'
	'gcc-4.6_unity'
	
	'gcc-4.7_debug'
	'gcc-4.7_unity'
	
	'gcc-4.8_debug'
	'gcc-4.8_unity'
	
	'gcc-4.9_debug'
	'gcc-4.9_unity'
	
	'gcc-4.10_debug'
	'gcc-4.10_unity'
	
	'mingw_debug'
	'mingw_unity'
	
	'msvc-9.0-32_unity'
	'msvc-10.0-32_unity'
	'msvc-11.0-32_unity'
	'msvc-12.0-32_debug'
	'msvc-12.0-64_unity'
	
	# Test different build types
	
	$default_compiler''
	$default_compiler'_unity_debug'
	$default_compiler'_unity_xtra'
	
	# Test different architectures
	
	$default_compiler'_m32_debug'
	$default_compiler'_m32'
	
	$default_compiler'_debug_minimal'
	$default_compiler'_unity_minimal_static'
	
	'gcc-freebsd-9.1-i686_debug'
	
	'gcc-armv6j-hf_unity_static'
	
	# Test different library versions
	
	$default_compiler'_debug_boost-1.48_boostfs'
	$default_compiler'_debug_boost-1.49_boostfs'
	$default_compiler'_debug_boost-1.50_boostfs'
	$default_compiler'_debug_boost-1.51_boostfs'
	$default_compiler'_debug_boost-1.52_boostfs'
	$default_compiler'_debug_boost-1.53_boostfs'
	$default_compiler'_debug_boost-1.54_boostfs'
	$default_compiler'_debug_boost-1.55_boostfs'
	
	$default_compiler'_olddeps'
	$default_compiler'_olddeps_debug'
	
	# TODO 'include-what-you-use'
	
	'style'
	'winstyle'
	
)

favicons['/favicon.ico']=''
favicons['/images/arx-libertatis.png']='128x128'
favicons['/favicon.png']='16x16'
