#!/bin/bash

# What is the project called
project_name='Arx'

# Some additional arx-specific build options
cmake_options[minimal]='-DBUILD_EDIT_LOADSAVE=0'
cmake_options[unity]='-DUNITY_BUILD=1'
cmake_options[xtra]='-DDEBUG_EXTRA=1'
cmake_options[boostfs]='-DUSE_NATIVE_FS=0'

# The environments for these don't have Qt installed - disable the crash reporter
cmake_options[gcc-freebsd-9.1-i686]+=" -DBUILD_CRASHREPORTER=0"
cmake_options[gcc-armv6j-hf]+=" -DBUILD_CRASHREPORTER=0"

cmake_options[olddeps]+=" -DUSE_QT5=0"
cmake_options[m32]+=" -DUSE_QT5=0"
cmake_options[msvc-9.0-32]+=" -DUSE_QT5=0"
cmake_options[msvc-10.0-32]+=" -DUSE_QT5=0"

# Compiler for builds that test library/config compatability
default_compiler='gcc-4.7'

# Declare directories containing source code (for cppcheck and flawfinder)
source_directories+=(
	"$repo/tools"
)
include_directories+=(
	-I "$repo/tools"
)

# Finally, define the used build types.
# Each build type is an underscore-seperated list of tokens defined in
# cmake_options, compiler_options and make_options.
build_types=(
	
	# Test different compilers/stdlibs and versions
	
	'clang-3.0_libcxx_debug'
	'clang-3.0_libcxx_unity'
	
	'clang-3.1_libcxx_debug'
	'clang-3.1_libcxx_unity'
	
	'clang-3.2_libcxx_debug'
	'clang-3.2_libcxx_unity'
	
	'clang-3.3_libcxx_debug'
	'clang-3.3_libcxx_unity'
	
	'clang-dev_libcxx_debug'
	'clang-dev_libcxx_unity'
	
	'clang-dev_libcxx_m32_debug'
	
	'clang_libstdcxx_debug'
	'clang_libstdcxx_unity'
	
	# Broken for arx as of 5.0.0_pre20130113
	#'ekopath_debug'
	#'ekopath_unity'
	
	'icc_debug'
	'icc_unity'
	
	'gcc-4.3_debug'
	'gcc-4.3_unity'
	
	'gcc-4.4_debug'
	'gcc-4.4_unity'
	
	'gcc-4.5_debug'
	'gcc-4.5_unity'
	
	'gcc-4.6_debug'
	'gcc-4.6_unity'
	
	'gcc-4.7_debug'
	'gcc-4.7_unity'
	
	'gcc-4.8_debug'
	'gcc-4.8_unity'
	
	'gcc-4.9_debug'
	'gcc-4.9_unity'
	
	'mingw_debug'
	'mingw_unity'
	
	'msvc-9.0-32_debug'
	'msvc-10.0-32_debug'
	
	# Test different build types
	
	$default_compiler''
	$default_compiler'_unity_debug'
	$default_compiler'_unity_xtra'
	
	# Test different architectures
	
	$default_compiler'_m32_debug'
	$default_compiler'_m32'
	
	$default_compiler'_debug_minimal'
	$default_compiler'_unity_minimal'
	
	'gcc-freebsd-9.1-i686_debug'
	
	'gcc-armv6j-hf_unity_static'
	
	# Test different library versions
	
	$default_compiler'_debug_boost-1.39'
	$default_compiler'_debug_boost-1.41'
	$default_compiler'_debug_boost-1.42'
	$default_compiler'_debug_boost-1.45_boostfs'
	$default_compiler'_debug_boost-1.46_boostfs'
	$default_compiler'_debug_boost-1.47_boostfs'
	$default_compiler'_debug_boost-1.48_boostfs'
	$default_compiler'_debug_boost-1.49_boostfs'
	$default_compiler'_debug_boost-1.50_boostfs'
	$default_compiler'_debug_boost-1.51_boostfs'
	$default_compiler'_debug_boost-1.52_boostfs'
	$default_compiler'_debug_boost-1.53_boostfs'
	$default_compiler'_debug_boost-1.54_boostfs'
	
	$default_compiler'_olddeps'
	
	# Static analyzers and style checks
	
	'clang-analyzer'
	'clang-analyzer_unity'
	
	'cppcheck'
	
	'flawfinder'
	
	# TODO 'include-what-you-use'
	
	'style'
	'winstyle'
	
)

ignored_branches=(
	'gamma'
	'renderer_stack'
	'player_cleanup'
	'arx_edit'
	'rtt-experiment'
)

false_positives+=(
	'gcc-4.8_unity*'
	'gcc-4.9_unity*'
	'ekopath_*' # compiler crashes
)