#!/bin/sh

cd "$(dirname "$0")"
here="$(pwd)"

source "$here/common"

if [ "$1" == '-f' ] ;
	then force='1'
	else force=''
fi

function count() {
	
	local file="$1"
	local type="$2"
	
	local name="${file##*/}"
	local filter=0
	for i in "${ignore_anonymous_ns_warnings[@]}" ; do
		if [[ "$name" == $i ]] ; then
			local filter=1
		fi
	done
	if [ $filter == 1 ]
		then grep -P ".*\\.(cpp|h|hpp)\\:\d+(\\:\d+)?\\: $type" "$file" | grep -vP 'ub_.*\.cpp\:\d+\:\d+\: warning\: \[' | grep -v "the anonymous namespace" | wc -l
		else grep -P ".*\\.(cpp|h|hpp)\\:\d+(\\:\d+)?\\: $type" "$file" | grep -vP 'ub_.*\.cpp\:\d+\:\d+\: warning\: \[' | wc -l
	fi
}

function handle_build() {
	
	local file="$1"
	local allow_false_positives="$2"
	
	local name="${file%.ref}"
	local name="${name##*/}"
	local commit=`cat "$file"`
	
	local has_false_positives=0
	for i in "${false_positives[@]}" ; do
		if [[ "$name" == $i ]] ; then
			local has_false_positives=1
		fi
	done
	if [ $has_false_positives != $allow_false_positives ] ; then
		return
	fi
	
	local loc="commits/$commit/$name"
	local prefix="$logs/$loc"
	
	if [ ! -e "$prefix.txt" ] ; then
		echo "Skipping missing/incomplete '${esc}[33m$name${esc}[0m' at commit ${esc}[34m$commit${esc}[0m"
		return
	fi
	
	local warnings=`count "$prefix.txt" 'warning\:'`
	local errors=`count "$prefix.txt" 'error\:'`
	local fatal_errors=`count "$prefix.txt" 'fatal error\:'`
	local linker_errors=`count "$prefix.txt" 'undefined reference to'`
	local errors=$(($errors+$linker_errors))
	local errors=$(($errors+$fatal_errors))
	
	local time=`grep user "$prefix-time.txt" 2> /dev/null`
	local time="${time##* }"
	
	local minutes=`echo "$time" | sed -r 's/^user\t(.*)m(.*)s$/\1/g'`
	local seconds=`echo "$time" | sed -r 's/^user\t(.*)m(.*)s$/\2/g'`
	
	echo "${esc}[34m$name${esc}[0m:   $warnings warnings,   $errors errors,   $minutes min $seconds s"
	
	local wprefix="$toroot/$loc"
	
	echo "<tr>" >> "$index"
	echo "	<td><a href=\"$wprefix.htm\">$name</td>" >> "$index"
	echo "	<td align=right class='w w$warnings'><b>$warnings</b> warnings</td>" >> "$index"
	echo "	<td align=right class='e e$errors'><b>$errors</b> errors</td>" >> "$index"
	echo "	<td align=right>$minutes min</td><td align=right>$seconds s</td>" >> "$index"
	echo "	<td><a href=\"$wprefix.txt\">[txt]</a></td>" >> "$index"
	echo "	<td><a href=\"$wprefix-raw.txt\">[raw]</a></td>" >> "$index"
	echo "	<td><a href=\"$wprefix-options.txt\">[opt]</a></td>" >> "$index"
	echo "	<td><a href=\"$wprefix-config.txt\">[cfg]</a></td>" >> "$index"
	echo "</tr>" >> "$index"
	
}

function handle_context() {
	
	local type="$1"
	local dir="$2"
	
	local context="${dir##*/}"
	
	toroot='../..'
	
	context=${dir##*/}
	
	index="$dir/index.htm"
	
	if [ "$dir" -nt "$index" ] || [ "$force" ]
		then echo "Updating '${esc}[36m$context${esc}[0m'..."
		else return
	fi
	
	html_header "Arx Build Logs for $type $context" "$toroot" > "$index"
	echo "<h1>Build logs for $type $context</h1>" >> "$index"
	echo "<a href=\"../\">Other Logs</a><br><br>" >> "$index"
	
	echo "<table cellspacing=1 cellpadding=2>" >> "$index"
	for f in `dir -d $dir/*.ref 2> /dev/null` ; do
		handle_build "$f" 0
	done
	echo "</table>" >> "$index"
	
	echo "<h2>Build logs that may contain false positives:</h2>" >> "$index"
	echo "<table cellspacing=1 cellpadding=2>" >> "$index"
	for f in `dir -d $dir/*.ref 2> /dev/null` ; do
		handle_build "$f" 1
	done
	echo "</table>" >> "$index"
	
	html_footer >> "$index"
	
}

echo "Updating indices..."

for f in `dir -d $logs/branches/* 2> /dev/null` ; do
	handle_context 'branch' "$f"
done

for f in `dir -d $logs/commits/* 2> /dev/null` ; do
	handle_context 'commit' "$f"
done

echo "Done."
