#!/bin/bash

# Code shared between autobuild and buildstats.

source "$here/config"

# Color code escape character.
esc=`echo -e '\033'`

html_header() {
	
	local title="$1"
	local toroot="$2"
	
	local lt='<'
	
	echo "${lt}html>${lt}head>${lt}title>$title</title>"
	echo '<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">'
	echo "<link rel=\"stylesheet\" href=\"$toroot/console.css\" type=\"text/css\">"
	echo '</head><body>'
	
}

html_footer() {
	echo '</body></html>'
}

function parse_build_type() {
	
	local build_type="$1"
	local out_name="$2"
	
	IFS='_' read -ra components <<< "$build_type"
	
	eval "$2=( ${components[@]} )"
}

function in_array() {
	
	local needle="$1"
	
	for entry in "${@:2}" ; do
		if [ "$entry" == "$needle" ] ; then
			true
			return
		fi
	done
	
	false
}

function in_wildcard_array() {
	
	local needle="$1"
	
	for entry in "${@:2}" ; do
		if [[ "$needle" == $entry ]] ; then
			true
			return
		fi
	done
	
	false
}
