#!/bin/sh

# Where the local git repository is located there mus be no changes to the working tree.
repo="$here/repo"

# Directory to use for building.
build="$here/build"

# Where to save the resulting logs. (must end in 'logs' for stats to work)
logs="$here/logs"

# Where to save the resulting binaries.
bin="$here/bin"

# Location of temporary log files.
log_build="$build/buildlog"
log_config="$build/config.txt"

# What part if the checkt out repo to build (location of the CMakeLists.txt)
path=''

# Declare possible build options (passed to cmake).
declare -A compiler_options
compiler_options[gcc44]='-DCMAKE_CXX_FLAGS=-B/usr/x86_64-pc-linux-gnu/gcc-bin/4.4.5/'
compiler_options[gcc45]='-DCMAKE_CXX_FLAGS=-B/usr/x86_64-pc-linux-gnu/gcc-bin/4.5.2/'
compiler_options[gcc46]='-DCMAKE_CXX_FLAGS=-B/usr/x86_64-pc-linux-gnu/gcc-bin/4.6.0/'
compiler_options[clang]="-DARX_USE_CLANG=1 -DCMAKE_CXX_FLAGS=-B$here/fakegcc/clang/"
compiler_options[clang_analyzer]="-DARX_USE_CLANG=1 -DCMAKE_CXX_FLAGS=-B$here/fakegcc/clang-analyzer/"
compiler_options[mingw32]="-DCMAKE_TOOLCHAIN_FILE=$here/mingw-toolchain.cmake \"-DCMAKE_CXX_FLAGS=-isystem /usr/include/wine/windows\" -DARX_BUILD_TOOLS=0"
compiler_options[m32]='-DARX_FORCE_32BIT=1'
compiler_options[m64]='-DARX_FORCE_32BIT=0'
compiler_options[dbg]='-DARX_DEBUG=1'
compiler_options[opt]='-DARX_DEBUG=0'
compiler_options[xtra]='-DARX_DEBUG_EXTRA=1'
compiler_options[unity]='-DARX_USE_UNITYBUILD=1'
compiler_options[noeditor]='-DARX_BUILD_EDITOR=0'
compiler_options[lto]='-DARX_USE_LTO=1'

false_positives=( 'clang_analyzer' '_xtra' )
