#!/bin/sh

if [ "$project" == "" ] ; then
	project='arx'
fi

# Where the local git repository is located there mus be no changes to the working tree.
repo="$here/repo/$project"

# Directory to use for building.
build="$here/build"

# Where to save the resulting logs. (must end in 'logs' for stats to work)
logs="$here/logs/$project"

# Where to save the resulting binaries.
bin="$here/bin/$project"

# Where to find additional toolchains.
toolchains="$here/toolchains"

# Location of temporary log files.
log_build="$build/buildlog"
log_config="$build/config.txt"

# What part of the checked-out repo to build (location of the CMakeLists.txt)
path=''

# Declare possible build options (passed to cmake).
declare -A cmake_options
cmake_options=(
	[gcc-4.3]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/gcc-4.3-toolchain.cmake\""
	[gcc-4.4]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/gcc-4.4-toolchain.cmake\""
	[gcc-4.5]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/gcc-4.5-toolchain.cmake\""
	[gcc-4.6]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/gcc-4.6-toolchain.cmake\""
	[gcc-4.7]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/gcc-4.7-toolchain.cmake\""
	[gcc-4.8]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/gcc-4.8-toolchain.cmake\""
	[clang]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/clang-toolchain.cmake\""
	[ekopath]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/ekopath-toolchain.cmake\""
	[clang-analyzer]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/clang-analyzer-toolchain.cmake\""
	[include-what-you-use]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/include-what-you-use-toolchain.cmake\""
	[mingw]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/mingw-toolchain.cmake\""
	[winelib]="\"-DCMAKE_TOOLCHAIN_FILE=$toolchains/wine-toolchain.cmake\""
	[debug]='-DCMAKE_BUILD_TYPE=Debug'
	[boost-1.37]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_37/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_37/'
	[boost-1.39]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_39/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_39/'
	[boost-1.41]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_41/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_41/'
	[boost-1.42]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_42/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_42/'
	[boost-1.45]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_45/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_45/'
	[boost-1.46]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_46/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_46/'
	[boost-1.47]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_47/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_47/'
	[boost-1.48]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_48/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_48/'
	[boost-1.49]='-DBOOST_INCLUDEDIR=/usr/include/boost-1_49/ -DBOOST_LIBRARYDIR=/usr/lib64/boost-1_49/'
)

# Declare possible build options (passed to the compiler).
declare -A compiler_options
compiler_options=(
	[mingw]="-isystem $toolchains/dxerr/"
	[winelib]="-isystem $toolchains/dxerr/"
	[m32]='-m32'
)

# Declare possible build options (passed to make).
declare -A make_options
make_options=(
	[style]='style'
	[doxygen]='doc'
)

# Declare compiler-specific scripts to process build logs.
declare -A process

# Define how buildstats counts errors and warnings.
# Numbered entries are used for all builds.
# For other entries, the key is matched agains the build type.

# Declare patterns that count as a warning.
declare -A count_warnings
count_warnings=(
	[0]='\:\d+\: warning\:'
	['ekopath_*']='pathCC WARNING\:'
	['style']='.*\.(cpp|h|hpp)\:\d+\:|Can'"'"'t open for reading'
	['include-what-you-use']='The full include-list for .*\:'
)

# Declare patterns that count as an error.
declare -A count_errors
count_errors=(
	[0]='\:\d+\: error\:'
	[1]='\:\d+\: fatal error\:'
	[2]='\:(\d+|\(.*\))\: undefined reference to '
	[3]='ld\: cannot find'
	[3]='could not read symbols\: File in wrong format'
)

# Declare patterns for warnings that should be ignored.
declare -A ignore_warnings
ignore_warnings=(
	[0]='ub_.*\.cpp\:\d+\:(\d+\:)? warning\: (\[|ignoring \#pragma message)'
	['ekopath_*']='the anonymous namespace'
)

# Declare which build types have known false positive warnings/errors.
false_positives=(
	'include-what-you-use'
	'clang-analyzer'
	'*_xtra'
	'ekopath_*_opt'
	'gcc-4.3*'
	'gcc-4.4*'
)
