#!/bin/bash

# Modify the parameters so clang --analyze won't complain.
args=( )
compile=0
for var in "$@" ; do
	if [ "$var" = "-c" ] ;
		then compile=1
		else args+=( "$var" )
	fi
done

[ $compile == 1 ] && clang-9999 --analyze "${args[@]}"

# Actually compile something so that linking won't fail (especially important for the cmake run)
clang-9999 "$@" -O0 &> /dev/null
