#!/bin/sh

# TODO consider using c++-analyzer shipped with cmake, but it produces XML output.

IWYU_EXE='/home/dscharrer/pro/llvm/build/Release/bin/include-what-you-use'

# Modify the parameters so include-what-you-use won't complain.
args=( )
compile=0
for var in "$@" ; do
	if [ "$var" == "-c" ] ;
		then compile=1
		else args[${#args[*]}]="$var"
	fi
done

if [ $compile == 1 ] ; then
	"${IWYU_EXE}" "${args[@]}" 2>&1 \
	 | grep -v "^warning\\: .*\\: 'linker' input unused when '\\-fsyntax-only' is present$" \
	 | grep -vP "\\n\\(.* has correct \\#includes\\/fwd-decls\\)" \
	 | grep -vP "^---$"
fi

# Actually compile something so that linking won't fail (especially important for the cmake run)
clang++ "$@" &> /dev/null
