#!/bin/bash

if [ -t 1 ] && [ "$(tput colors 2> /dev/null)" != -1 ] ; then
	green="$(printf '\033[1;32m')"
	reset="$(printf '\033[m')"
else
	green=''
	reset=''
fi

paths=()
flags=()

declare -A shell_shebangs
shell_shebangs=(
	['#!/bin/sh']=1
	['#!/bin/bash']=1
	['#!/usr/bin/env bash']=1
)

mode=0
for arg in "$@" ; do
	
	if [ $mode != 2 ] ; then
		case "$arg" in
			--) mode=2 ; continue ;;
			-*) mode=1 ; flags+=("$arg") ; continue ;;
		esac
	fi
	
	# Treat tokens after -options as arguments
	if [ $mode = 1 ] ; then
		mode=0 ; flags+=("$arg") ; continue
	fi
	
	paths+=("$arg")
	
done

for path in "${paths[@]}" ; do
	while IFS= read -r -d '' file; do
		
		shebang="$(head -n1 "$file")"
		[ "${shell_shebangs["$shebang"]}" = 1 ] || continue;
		
		printf '%sChecking shell script %s%s\n' "$green" "$file" "$reset"
		
		shellcheck "${flags[@]}" "$file"
		
	done < <(find "$path" -not -path '*/\.*' -type f -executable -print0 | sort -z)
done
