#!/bin/sh

# pathCC doesn't like the -B argument that tells wine which compiler to use
args=( )
for var in "$@" ; do
	if [[ "$var" != -B* ]] ; then
		args[${#args[*]}]="$var"
	fi
done

/opt/ekopath-bin-4.0.10_pre20110717/bin/pathCC "${args[@]}" -D__builtin_ms_va_list=__builtin_va_list -Dms_abi=
